//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_NHOM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPN
    {
        public string MaPN { get; set; }
        public string MaSach { get; set; }
        public int SoLuongNhap { get; set; }
        public decimal GiaNhap { get; set; }
    
        public virtual PhieuNhap PhieuNhap { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
