//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_NHOM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DanhSachQuyen
    {

        [Display(Name = "Tên nhóm")]
        [Required(ErrorMessage = "Bạn chưa nhập tên nhóm")]
        public string IDNhom { get; set; }
        [Display(Name = "Tên quyền")]
        [Required(ErrorMessage = "Bạn chưa nhập tên quyền")]
        public string IDQuyen { get; set; }
        public string MoTa { get; set; }

        public virtual NhomNhanVien NhomNhanVien { get; set; }
        public virtual Quyen Quyen { get; set; }
    }
}
