//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_NHOM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.ChiTietHDs = new HashSet<ChiTietHD>();
        }
    
        [DisplayName("Mã hóa đơn")]
        public string MaHD { get; set; }
        [DisplayName("Tình trạng")]
        public int TinhTrang { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [DisplayName("Ngày xuất kho")]
        public Nullable<System.DateTime> NgayXuatKho { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [DisplayName("Ngày giao")]
        public Nullable<System.DateTime> NgayGiao { get; set; }
        [DisplayName("Tên khách hàng")]
        public string TenKH { get; set; }
        [DisplayName("Địa chỉ giao")]
        public string DiaChiGiao { get; set; }
        [DisplayName("Số điện thoại")]
        public string SoDT { get; set; }
        /*[DisplayName("")]*/
        public string MaNV { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHD> ChiTietHDs { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
