//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_NHOM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class NhaCungCap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhaCungCap()
        {
            this.PhieuNhaps = new HashSet<PhieuNhap>();
        }

        [DisplayName("Mã nhà cung cấp")]
        public string MaNCC { get; set; }
        [Required(ErrorMessage = "Chưa nhập nhà cung cấp")]
        [DisplayName("Nhà cung cấp")]
        public string TenNCC { get; set; }
        [Required(ErrorMessage = "Chưa nhập địa chỉ")]
        [DisplayName("Địa chỉ")]
        public string DiaChiNCC { get; set; }
        [Required(ErrorMessage = "Chưa nhập số điện thoại")]
        [DisplayName("Số điện thoại")]
        public string SDTNCC { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuNhap> PhieuNhaps { get; set; }
    }
}
