//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_NHOM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class NhaXuatBan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhaXuatBan()
        {
            this.Saches = new HashSet<Sach>();
        }

        [DisplayName("Mã nhà xuất bản")]
        public string MaNXB { get; set; }
        [Required(ErrorMessage = "Chưa nhập nhà xuất bản")]
        [DisplayName("Nhà xuất bản")]
        public string TenNXB { get; set; }
        [Required(ErrorMessage = "Chưa nhập địa chỉ")]
        [DisplayName("Địa chỉ")]
        public string DiaChiNXB { get; set; }
        [Required(ErrorMessage = "Chưa nhập số điện thoại")]
        [DisplayName("Số điện thoại")]
        public string DienThoai { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sach> Saches { get; set; }
    }
}
