//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_NHOM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sach()
        {
            this.ChiTietHDs = new HashSet<ChiTietHD>();
            this.ChiTietPNs = new HashSet<ChiTietPN>();
            this.Sach_TG = new HashSet<Sach_TG>();
        }        

        [DisplayName("Mã sách")]
        public string MaSach { get; set; }
        [Required(ErrorMessage = "Chưa nhập tên sách")]
        [DisplayName("Tên sách")]
        public string TenSach { get; set; }
        [Required(ErrorMessage = "Chưa nhập tên tác giả")]
        [DisplayName("Tác giả")]
        public string TenTG { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [DisplayName("Ngày xuất bản")]
        public System.DateTime NgayXB { get; set; }
        [DisplayName("Số lượng tồn")]
        public int SoLuongTon { get; set; }
        [DisplayName("Mô tả")]
        public string MoTa { get; set; }
        [DisplayName("Ảnh bìa")]
        public string AnhBia { get; set; }
        [DisplayName("Giá sách")]
        public decimal GiaSach { get; set; }
        [DisplayName("Thể loại")]
        public string MaTL { get; set; }
        [DisplayName("Nhà xuất bản")]
        public string MaNXB { get; set; }
        [DisplayName("Ngôn ngữ")]
        public string MaNN { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHD> ChiTietHDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPN> ChiTietPNs { get; set; }
        public virtual NgonNgu NgonNgu { get; set; }
        public virtual NhaXuatBan NhaXuatBan { get; set; }
        public virtual TheLoai TheLoai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sach_TG> Sach_TG { get; set; }
    }
}
