//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_NHOM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class TacGia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TacGia()
        {
            this.Sach_TG = new HashSet<Sach_TG>();
        }

        
        [DisplayName("Mã tác giả")]
        public string MaTG { get; set; }
        [Required(ErrorMessage = "Chưa nhập tên")]
        [DisplayName("Tác giả")]
        public string TenTG { get; set; }
        [Required(ErrorMessage = "Chưa nhập địa chỉ")]
        [DisplayName("Địa chỉ")]
        public string DiaChi { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sach_TG> Sach_TG { get; set; }
    }
}
