//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_NHOM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Don_Dat_hang
    {
        public string MaHD { get; set; }
        public string TenSach { get; set; }
        public string TenKH { get; set; }
        public string DiaChiGiao { get; set; }
        public string SoDT { get; set; }
        public decimal GiaBan { get; set; }
        public int SoLuongSach { get; set; }
        public Nullable<System.DateTime> NgayXuatKho { get; set; }
    }
}
